# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.pillar_layer0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_pillar_layer0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.pillar_layer1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_pillar_layer1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.pillar_layer2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_pillar_layer2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.stone_brick1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_stone_brick1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.stone_brick2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_stone_brick2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.stone_brick3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_stone_brick3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pillars.node.stone_brick4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_stone_brick4 set from storage animated_java:gu out