# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.death_pillar.frame matches 41.. run scoreboard players set @s aj.death_pillar.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.death_pillar.frame
execute at @s run function animated_java:pillars/animations/death_pillar/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.death_pillar.frame 1