# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pillars/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pillars.node.item_display] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display15] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display8] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,3f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display4] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,-1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display17] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1f,0f,0f,-1f,-1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display5] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display9] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display6] run data merge entity @s { transformation: [-1f,0f,0f,-1f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display7] run data merge entity @s { transformation: [-1f,0f,0f,1f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display10] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display13] run data merge entity @s { transformation: [-1f,0f,0f,1f,0f,1f,0f,1f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display11] run data merge entity @s { transformation: [-1f,0f,0f,-1f,0f,1f,0f,1f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display12] run data merge entity @s { transformation: [0f,0f,-1f,0f,0f,1f,0f,2f,1f,0f,0f,-1f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display14] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,4f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }