# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pillars/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pillars.node.pillar_layer0] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.pillar_layer1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.pillar_layer2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.stone_brick1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.stone_brick2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.stone_brick3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pillars.node.stone_brick4] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }