# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pillars rig_hash set value 'b2a2dbd5e964a59567b80d475d1b11a6a153311b4ca0807ebbbc2bf62273cfc8'
scoreboard objectives add aj.awake_pillar.frame dummy
scoreboard objectives add aj.idle_pillar.frame dummy
scoreboard objectives add aj.death_pillar.frame dummy
scoreboard objectives add aj.resetting_pillar.frame dummy
scoreboard objectives add aj.attack_stone_bricks.frame dummy
scoreboard objectives add aj.melee_pillar.frame dummy