# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pillars rig_hash set value '6c0d4bddf1de987637d1fe78def0d306c677f48edc4edfbba89a7ffdf57a2ae6'
scoreboard objectives add aj.awake_pillar.frame dummy
scoreboard objectives add aj.idle_pillar.frame dummy
scoreboard objectives add aj.death_pillar.frame dummy
scoreboard objectives add aj.spike_stone_bricks.frame dummy