# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pillars/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pillars.node.item_display] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.pillars.node.item_display2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }