# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.pillars.animation.awake_pillar.playing
tag @s remove aj.pillars.animation.idle_pillar.playing
tag @s remove aj.pillars.animation.death_pillar.playing
tag @s remove aj.pillars.animation.resetting_pillar.playing
tag @s remove aj.pillars.animation.attack_stone_bricks.playing
tag @s remove aj.pillars.animation.melee_pillar.playing