# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display3) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display15) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display8) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1903f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-2.8097f,0f,0f,-1f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display17) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.8097f,0f,0f,-1f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display5) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-2.8097f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display9) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.8097f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display6) {transformation: [-1f,0f,0f,-1f,0f,1f,0f,-2.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display7) {transformation: [-1f,0f,0f,1f,0f,1f,0f,-2.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display10) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8097f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display13) {transformation: [-1f,0f,0f,1f,0f,1f,0f,-1.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display11) {transformation: [-1f,0f,0f,-1f,0f,1f,0f,-1.8097f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display12) {transformation: [0f,0f,-1f,0f,0f,1f,0f,-0.8097f,1f,0f,0f,-1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display14) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.1903f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}