# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b2a2dbd5e964a59567b80d475d1b11a6a153311b4ca0807ebbbc2bf62273cfc8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack