# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0eb317fd8076e0d4a354f239d50558e491173df6b598db15cab4cca9e9ab529c'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack