# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '4a3441ddd44f9fff9ffeca65143fd28b3f840b887a1b2d6256b30ec528d03d03'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack